#!/bin/bash

sudo cp ./resources/systemd/* /etc/systemd/system/
sudo systemctl daemon-reload

sudo systemctl enable kaspa-mainnet
sudo systemctl enable kaspa-testnet-10
sudo systemctl enable kaspa-testnet-11
