#!/bin/bash

if [[ $1 == "start" ]]; then
	sudo systemctl start kaspa-mainnet kaspa-testnet-10 kaspa-testnet-11
elif [[ $1 == "stop" ]]; then
	sudo systemctl stop kaspa-mainnet kaspa-testnet-10 kaspa-testnet-11
elif [[ $1 == "status" ]]; then
	sudo systemctl status kaspa-mainnet kaspa-testnet-10 kaspa-testnet-11
elif [[ $1 == "restart" ]]; then
	sudo systemctl restart kaspa-mainnet kaspa-testnet-10 kaspa-testnet-11
else
    echo "Usage: kaspad start|stop|status|restart"
fi
